"""
Import reviewed flag candidates from a CSV into the v3 manifest JSONL files.

The CSV is expected to have the columns generated by
reports/import/wikipedia/cleaned/manifest_review.csv:

include,result_id,flag_id,display_name,category,status,variant,local_path,
source_url,license,review_status,trainable,notes

Usage:
    python scripts/import_manifest_review.py --csv reports/import/wikipedia/cleaned/manifest_review.csv --dry-run
    python scripts/import_manifest_review.py --csv reports/import/wikipedia/cleaned/manifest_review.csv
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_DIR = REPO_ROOT / "data" / "manifest"
REPORTS_DIR = REPO_ROOT / "reports" / "import" / "manifest_review"

VALID_CATEGORY = {
    "national",
    "subnational",
    "military",
    "maritime",
    "organization",
    "cultural",
    "pride",
    "sports",
    "other",
}
VALID_STATUS = {"current", "historical", "proposed", "unofficial", "disputed", "deprecated"}
VALID_VARIANT = {
    "standard",
    "civil",
    "state",
    "military",
    "royal",
    "presidential",
    "organizational",
    "alternate",
    "reconstruction",
    "ceremonial",
}
VALID_REVIEW_STATUS = {
    "imported",
    "needs_review",
    "needs_source",
    "needs_license",
    "needs_disambiguation",
    "reviewed",
    "rejected",
}


def _truthy(value: str) -> bool:
    return value.strip().lower() in {"1", "true", "yes", "y"}


def _load_jsonl(path: Path, id_field: str) -> dict[str, dict]:
    records: dict[str, dict] = {}
    if not path.exists():
        return records
    with open(path, encoding="utf-8", newline="") as f:
        for line in f:
            line = line.rstrip("\n").rstrip("\r")
            if not line:
                continue
            obj = json.loads(line)
            records[obj[id_field]] = obj
    return records


def _write_jsonl(path: Path, records: dict[str, dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        for rec in records.values():
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")


def _load_rows(csv_path: Path) -> list[dict[str, str]]:
    with open(csv_path, encoding="utf-8-sig", newline="") as f:
        rows = [dict(row) for row in csv.DictReader(f)]
    return [row for row in rows if _truthy(row.get("include", ""))]


def _source_name(source_url: str, path: str) -> str:
    if "commons.wikimedia.org" in source_url:
        return "Wikimedia Commons"
    if path.startswith("data/sources/local/"):
        return "Local"
    return "Unknown"


def _short_description(display_name: str, status: str) -> str:
    if status == "historical":
        return f"Historical flag: {display_name}."
    if status == "current":
        return f"Current flag of {display_name}."
    return f"Flag of {display_name}."


def _validate_row(row: dict[str, str], rownum: int) -> list[str]:
    errors: list[str] = []
    required = ["result_id", "flag_id", "display_name", "category", "status", "variant", "local_path", "review_status"]
    for field in required:
        if not row.get(field, "").strip():
            errors.append(f"row {rownum}: missing {field}")

    if row.get("category") not in VALID_CATEGORY:
        errors.append(f"row {rownum}: invalid category {row.get('category')!r}")
    if row.get("status") not in VALID_STATUS:
        errors.append(f"row {rownum}: invalid status {row.get('status')!r}")
    if row.get("variant") not in VALID_VARIANT:
        errors.append(f"row {rownum}: invalid variant {row.get('variant')!r}")
    if row.get("review_status") not in VALID_REVIEW_STATUS:
        errors.append(f"row {rownum}: invalid review_status {row.get('review_status')!r}")

    trainable = _truthy(row.get("trainable", ""))
    if trainable and row.get("review_status") != "reviewed":
        errors.append(f"row {rownum}: trainable rows must have review_status=reviewed")
    if trainable and not row.get("license", "").strip():
        errors.append(f"row {rownum}: trainable rows must have a license")

    local_path = row.get("local_path", "")
    if local_path and not (REPO_ROOT / local_path).exists():
        errors.append(f"row {rownum}: local_path does not exist: {local_path}")

    return errors


def main() -> None:
    parser = argparse.ArgumentParser(description="Import reviewed candidate flags into manifest JSONL files.")
    parser.add_argument("--csv", required=True, help="Reviewed manifest CSV path.")
    parser.add_argument("--dry-run", action="store_true", help="Validate and report without writing manifest files.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing reviewed records.")
    args = parser.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"ERROR: CSV not found: {csv_path}", file=sys.stderr)
        sys.exit(2)

    rows = _load_rows(csv_path)
    if not rows:
        print("ERROR: no included rows found.", file=sys.stderr)
        sys.exit(2)

    validation_errors: list[str] = []
    result_ids: set[str] = set()
    flag_ids: set[str] = set()
    for idx, row in enumerate(rows, 2):
        validation_errors.extend(_validate_row(row, idx))
        result_id = row.get("result_id", "")
        flag_id = row.get("flag_id", "")
        if result_id in result_ids:
            validation_errors.append(f"row {idx}: duplicate result_id in CSV: {result_id}")
        if flag_id in flag_ids:
            validation_errors.append(f"row {idx}: duplicate flag_id in CSV: {flag_id}")
        result_ids.add(result_id)
        flag_ids.add(flag_id)

    if validation_errors:
        print("ERROR: CSV validation failed:", file=sys.stderr)
        for error in validation_errors:
            print(f"  {error}", file=sys.stderr)
        sys.exit(1)

    results_path = MANIFEST_DIR / "results.jsonl"
    flags_path = MANIFEST_DIR / "flags.jsonl"
    assets_path = MANIFEST_DIR / "assets.jsonl"

    results = _load_jsonl(results_path, "result_id")
    flags = _load_jsonl(flags_path, "flag_id")
    assets = _load_jsonl(assets_path, "asset_id")

    report_records: list[dict] = []
    n_results = n_flags = n_assets = n_skipped = 0

    for row in rows:
        result_id = row["result_id"].strip()
        flag_id = row["flag_id"].strip()
        display_name = row["display_name"].strip()
        category = row["category"].strip()
        status = row["status"].strip()
        variant = row["variant"].strip()
        local_path = row["local_path"].strip()
        source_url = row.get("source_url", "").strip()
        license_value = row.get("license", "").strip()
        review_status = row["review_status"].strip()
        trainable = _truthy(row.get("trainable", ""))
        asset_id = f"{flag_id}-source"

        existing_result = results.get(result_id)
        existing_flag = flags.get(flag_id)
        existing_asset = assets.get(asset_id)
        protected = [
            ("result", result_id, existing_result),
            ("flag", flag_id, existing_flag),
            ("asset", asset_id, existing_asset),
        ]
        if not args.force:
            reviewed_existing = [
                f"{kind}:{rec_id}"
                for kind, rec_id, rec in protected
                if rec and rec.get("review_status") == "reviewed"
            ]
            if reviewed_existing:
                print(f"  SKIP protected reviewed records: {', '.join(reviewed_existing)}")
                n_skipped += 1
                report_records.append({
                    "flag_id": flag_id,
                    "outcome": "skipped_existing_reviewed",
                    "protected": reviewed_existing,
                })
                continue

        result_rec = {
            "result_id": result_id,
            "display_name": display_name,
            "category": category,
            "fictionality": "nonfiction",
            "status": status,
            "short_description": _short_description(display_name, status),
            "aliases": [display_name],
            "links": [{"label": "Source", "url": source_url}] if source_url else [],
            "review_status": review_status,
        }
        flag_rec = {
            "flag_id": flag_id,
            "result_id": result_id,
            "display_name": display_name,
            "variant": variant,
            "status": status,
            "review_status": review_status,
            "trainable": trainable,
        }
        asset_rec = {
            "asset_id": asset_id,
            "flag_id": flag_id,
            "asset_type": "source_original",
            "path": local_path,
            "source_name": _source_name(source_url, local_path),
            "source_url": source_url,
            "license": license_value,
            "review_status": review_status,
            "trainable": trainable,
        }

        if not args.dry_run:
            if result_id not in results:
                n_results += 1
            if flag_id not in flags:
                n_flags += 1
            if asset_id not in assets:
                n_assets += 1
            results[result_id] = result_rec
            flags[flag_id] = flag_rec
            assets[asset_id] = asset_rec
        else:
            n_results += int(result_id not in results)
            n_flags += int(flag_id not in flags)
            n_assets += int(asset_id not in assets)

        print(f"  IMPORT: {flag_id}")
        report_records.append({
            "flag_id": flag_id,
            "result_id": result_id,
            "asset_id": asset_id,
            "outcome": "imported",
        })

    if not args.dry_run:
        _write_jsonl(results_path, results)
        _write_jsonl(flags_path, flags)
        _write_jsonl(assets_path, assets)

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%S")
    report = {
        "version": 1,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source_csv": str(csv_path),
        "dry_run": args.dry_run,
        "summary": {
            "included_rows": len(rows),
            "new_results": n_results,
            "new_flags": n_flags,
            "new_assets": n_assets,
            "skipped_existing_reviewed": n_skipped,
        },
        "records": report_records,
    }
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / f"{ts}.json"
    with open(report_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
        f.write("\n")

    mode = "DRY RUN" if args.dry_run else "DONE"
    print(
        f"\n{mode}: {n_results} new results, {n_flags} new flags, "
        f"{n_assets} new assets, {n_skipped} skipped. Report: {report_path}"
    )


if __name__ == "__main__":
    main()
